### PR TITLE
Fix Unicode issue in tests

### PR DESCRIPTION
**Pull request by PeterMosmans**
See #42 from @SteinHeselmans : This commit enforces Unicode strings and fixes the nosetests.
Note that this commit is based on pull request #43 : I can rebase it on top of master, if you want to ?

Cheers,

Peter

### CODE REVIEW

**Comment by SteinHeselmans** [comment]
:+1:  nice

**Comment by SteinHeselmans** [comment]
two more errors from static checker:

sphinx_git/__init__.py:96: [R1705(no-else-return), GitCommitDetail._github_link] Unnecessary "else" after "return"
sphinx_git/__init__.py:160: [C1801(len-as-condition), GitChangelog._filter_commits_on_filenames] Do not use `len(SEQUENCE)` as condition value

if we fix those, i think CI passes :+1:

**Comment by PeterMosmans** [comment]
From what I can see that's perfectly doable @SteinHeselmans @OddBloke - however, should I base the fixes on master, or based on :arrow_up: pull requests ?
I could also amend this pull request (which is _not_ based on master). @OddBloke .. ?

**Comment by SteinHeselmans** [comment]
i would say those additions are welcome as well

**Comment by PeterMosmans** [comment]
Pheeuw, that took more commits than expected :cry: - tox for Python 3+ is (still) broken, I'm not going to touch that....

**Comment by SteinHeselmans** [comment]
would this work?

```
# Python 2 and 3: alternative 1
from builtins import str
templates = [u"blog/blog_post_detail_%s.html" % str(slug)]
```

from http://python-future.org/compatible_idioms.html

**Comment by PeterMosmans** [comment]
@SteinHeselmans Thanks, I didn't knew that site. Clever trick with platform-independent Unicode casting, nicer than my ugly try/except block.
One would expect that in 'normal' circumstances websites set the correct encoding headers for websites (e.g. utf-8), so then this becomes a non-issue.
The encoding is correctly 'guessed' on Python3 anyway.

I see it more as fixing the test cases, as it's a BeautifulSoup issue (it chooses the incorrect Unicode encoding).

**Comment by OddBloke** [comment]
Oops, I fixed these errors before seeing this PR; closing this out.

**Comment by OddBloke** [comment]
I've cherry-picked the commits that I didn't replicate in to #45.

**Pull request closed without merging**
