### PR TITLE
Add search_parent_directories=True to Repo creation.

### LINKED ISSUE #18: InvalidGitRepositoryError with latest version of GitPython
I believe this could be fixed by giving `Repo` the argument `search_parent_directories=True`.

### PR DESCRIPTION
**Pull request by pomalley**
Fixes #18 (error with new version of GitPython).

### CODE REVIEW

**Comment by pomalley** [comment]
OK, the pylint is failing because of "too few public methods". I'm guessing that should be disabled, because it seems like we really do want GitChangelog to only have `run`.

**Comment by OddBloke** [comment]
Will this work on versions of GitPython before the latest? Could you bump the requirement in setup.py if needed?

Agreed that it's a spurious pylint failure, can you add an ignore?

Other than those two things, looks good. :)

**Comment by pomalley** [comment]
I can do those things.

The other point is that I didn't add a test for this (correctly opening the repo) because, well, I didn't know how to, since the tests are all based on a mock repo. Ideas?

**Comment by pomalley** [comment]
Apparently [pylint no longer supports python2.6](https://bitbucket.org/logilab/pylint/issue/390/py26-compatiblity-broken) which is why the first travis build fails.

**Comment by pomalley** [comment]
I don't mean to keep pestering you but it would be cool to get this merged in. Would you like to remove python2.6 support, or do something else about pylint?

**Comment by OddBloke** [comment]
I've pinned PyLint and astroid to versions which supports Python 2.6, at least for now. If you rebase on to master, you should see Travis success. :)

**Comment by pomalley** [comment]
Well, how about that. :-)

**Comment by OddBloke** [comment]
Merged; thanks for your contribution!

**Comment by OddBloke** [comment]
Released in version 9. Thanks again!

**Pull request merged**
