### PR TITLE
add option repo-dir

### PR DESCRIPTION
**Pull request by boeddeker**
With this option it is possible to get the change log of another repository

Example
.. git_changelog::
   :repo-dir: ../../relative/path/to/another/repo

### CODE REVIEW

**Comment by t2y** [comment]
How about adding 3.5 to travis.yml?

* https://docs.travis-ci.com/user/languages/python

**Comment by boeddeker** [comment]
On my computer it's working with python 3.5.

**Comment by OddBloke** [comment]
Hi boeddeker,

Thanks for taking the time to look at this!

There are a lot of changes in this PR other than adding the repo-dir option; could you resubmit this with just the repo-dir changes on top of my master branch, please?

(Also, please add some tests for the repo-dir option. :)


Thanks,

Dan

**Comment by boeddeker** [comment]
Hi Dan,

I am only working with Python 3, so I need the modifications of XonqNopp. Is it possible that you add Python 3 support for sphinx-git?

I will write some tests and make a PR, if there is a solution for Python 3.

Best regards
Christoph

**Pull request closed without merging**
